name: Node.js

on:
  push:
  pull_request:
  schedule:
    # every 5th of the month on 4:32 UTC
    - cron: '32 4 5 * *'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 16
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test
